<!--FALTA EL BOTON EXPORTAR Y AGREGAR -->

<!--page specific css styles-->
<link rel="stylesheet" href="<?php echo $this->baseUrl ?>/assets/data-tables/DT_bootstrap.css" />

<script>
    
        function test1(ruc){

            $('#modal-2 .modal-body').html("<div class='progress progress-striped active'>\n\
                                            <div style='width: 45%;' class='bar'></div>\n\
                                            </div>");
        
            $('#modal-2 .modal-body').load('<?php echo $this->baseUrl ?>/proveedor/viewrecord/ruc/'+ruc)
        }
    
    $(document).ready(function(){
       

        
        if (jQuery().dataTable) {
            $("#table1").dataTable({
                bScrollCollapse: true,                
                bProcessing: true,
                bServerSide: true,
                sAjaxSource: "<?php echo $this->baseUrl ?>/proveedor/listarproveedores",                
                aLengthMenu: [
                    [10, 15, 25, 50, 100, -1],
                    [10, 15, 25, 50, 100, "All"]
                ],
                iDisplayLength: 10,
                oLanguage: {
                    sLengthMenu: "_MENU_ Registros por pagina",
                    sInfo: "_START_ - _END_ of _TOTAL_",
                    sInfoEmpty: "0 - 0 of 0",
                    oPaginate: {
                        sPrevious: "Prev",
                        sNext: "Next"
                    }
                },
                 aoColumns: [
                 null ,  
                 {  "bSearchable": false,
                    "bSortable": false
                 }        
                , 
                { "bVisible": true}, 
                null, 
                null,
                null, 
                null,
                null,
                { "sName": "ACTION",
                  "bSearchable": false,
                  "bSortable": false,
                  "fnRender": function (oObj) {
                     return " <div class='btn-group'>\n\
                            <a onclick='test1(" + oObj.aData[0] + ")' class='btn btn-small show-tooltip' title='View' href='#modal-2' data-toggle='modal' ><i class='icon-zoom-in'></i></a>\n\
                            <a class='btn btn-small show-tooltip' title='Edit' href='<?php echo $this->baseUrl ?>/proveedor/update/ruc/" + oObj.aData[0] + "'><i class='icon-edit'></i></a>\n\
                            <a class='btn btn-small btn-danger show-tooltip' title='Delete' href='<?php echo $this->baseUrl ?>/proveedor/delete/ruc/" + oObj.aData[0] + "'><i class='icon-trash'></i></a></div>  ";
                   }
                }
                        
              ]          
                          
       
            })
        }
              
        


    })
    
    


</script>


            <!-- BEGIN Content -->
            <div id="main-content">
                <!-- BEGIN Page Title -->
                <div class="page-title">
                    <div>
                        <h1><i class="icon-file-alt"></i> Proveedores</h1>
                        <h4>Mantenimiento de Proveedores</h4>
                    </div>
                </div>
                <!-- END Page Title -->

                <!-- BEGIN Breadcrumb -->
                <div id="breadcrumbs">
                    <ul class="breadcrumb">
                        <li>
                            <i class="icon-home"></i>
                            <a href="<?php echo $this->baseUrl ?>">Home</a>
                            <span class="divider"><i class="icon-angle-right"></i></span>
                        </li>
                        <li class="active">Proveedor</li>
                    </ul>
                </div>
                <!-- END Breadcrumb -->

                <!-- BEGIN Main Content -->
                <div class="row-fluid">
                    <div class="span12">
                        <div class="box">
                            <div class="box-title">
                                <h3><i class="icon-table"></i> Lista de Proveedores</h3>
                                <div class="box-tool">
                                    <a data-action="collapse" href="#"><i class="icon-chevron-up"></i></a>
                                    <a data-action="close" href="#"><i class="icon-remove"></i></a>
                                </div>
                            </div>
                            <div class="box-content">
                                <div class="btn-toolbar pull-right clearfix">
                                    <div class="btn-group">
                                        <a class="btn btn-circle show-tooltip" title="Nuevo proveedor" href="<?php echo "$this->baseUrl" ?>/proveedor/add"><i class="icon-plus"></i></a>
                                    </div>
                                    <div class="btn-group">
                                        <a class="btn btn-circle show-tooltip" href="<?php echo "$this->baseUrl" ?>/proveedor/exportarpdf" title="Imprimir"><i class="icon-print"></i></a>
                                        <a class="btn btn-circle show-tooltip" href="<?php echo "$this->baseUrl" ?>/proveedor/exportarpdf" title="Exportar PDF" ><i class="icon-file-text-alt"></i></a>
                                        <a class="btn btn-circle show-tooltip" href="<?php echo "$this->baseUrl" ?>/proveedor/exportarexcel" title="Exportar Excel" ><i class="icon-table"></i></a>
                                    </div>
                                    <div class="btn-group">
                                        <a class="btn btn-circle show-tooltip" title="Refresh" href="#"><i class="icon-repeat"></i></a>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
<table class="table table-advance" id="table1">
    <thead>
        <tr>
            <th>RUC</th>
            <th>categoria</th>
            <th>nombre</th>
            <th>direccion</th>
            <th>departamento</th>
            <th>provincia</th>
            <th>distrito</th>
            <th>telefono_fijo</th>
            <!--<th class="text-center">telefono_celular</th>
            <th>mail</th>
            <th>costo</th>
            <th>observacion</th>
            <th>user</th>
            <th>fecha</th>-->            
            <th style="width:100px">Accion</th>
        </tr>
    </thead>
    <tbody>
            <tr>
		<td colspan="5" class="dataTables_empty">
                                <div class="progress progress-striped active">
                                    <div style="width: 45%;" class="bar"></div>
                                </div>
                </td>
            </tr>
    </tbody>
</table>
                            </div>
                        </div>
                    </div>
                </div>

    <div id="modal-2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel1">Proveedor</h3>
        </div>
        <div class="modal-body">
            
            
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" data-dismiss="modal">Aceptar</button>
        </div>
    </div>                
                
                
            
        <!--page specific plugin scripts-->
        <script type="text/javascript" src="<?php echo $this->baseUrl ?>/assets/data-tables/jquery.dataTables.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl ?>/assets/data-tables/DT_bootstrap.js"></script>
            

