<fieldset>
<legend></legend>
<?php echo $this->form; ?>
</fieldset>

<style>
fieldset{

	border: 1px solid;
	
}


#fieldset-left{
	float:left;
	border:none;
}

#fieldset-right{
	float:left;
	border:none;	
}

#fieldset-bottom{
	clear:both;
	border:none;	
}

#observacion{
	height: 100px;
}

/* Cambiar para cada formulario*/
#idproveedor-label{
	display:none;
}

#submitbutton{
	margin-left: 229px;
}

</style>


<script>


$('dl').addClass('dl-horizontal');

$('#RUC').attr('placeholder','digite 11 digitos')
$('#RUC').attr('readonly','')
$('#observacion').attr('rows','5')

</script>

<script>


	$('#iddepartamento').change( function(e){
	
		var codDepa = $(this).val()
		//alert(codDepa)
		$.get('<?php echo $this->url(array('controller' => 'proveedor','action' => 'listarprov') ); ?>',{  codDepa:codDepa }, function(data) {
			
			$('#idprovincias').empty()	
			$('#iddistrito').empty()	
			
			$('#idprovincias').append("<option value='0'>select</option>")			
			$.each($.parseJSON(data), function(index, value) {
				$('#idprovincias').append("<option value="+value[0]+">"+value[1]+"</option>")
			  
			});

		});
			
		
	})


	$('#idprovincias').change( function(e){

		var codDistr = $(this).val()
		$.get('<?php echo $this->url(array('controller' => 'proveedor','action' => 'listardistri') ); ?>',{  codDistr:codDistr }, function(data) {
			
			$('#iddistrito').empty()
			
			$('#iddistrito').append("<option value='0'>select</option>")			
			$.each($.parseJSON(data), function(index, value) {
				$('#iddistrito').append("<option value="+value[0]+">"+value[1]+"</option>")
			  
			});

		});
			
		
	})

    
</script>

