<!--creo link para agregar un album -->

<table>
    <tr style="border:none;background:none"> 
        <td style="border:none;background:none">  
            <a href="<?php echo $this->url(array('controller' => 'cementerio','action' => 'add')); ?>"> 
                <img src="<?php echo $this->baseUrl ?>/images/add.gif" title="Agregar">
            </a>    
        </td>    
        <td style="border:none;background:none"> 
            <a href="<?php echo $this->url(array('controller' => 'cementerio','action' => 'add')); ?>">         
            Cementerio
            </a>
        </td> 
    </tr>    
</table>


<!--creo una tabla para mostrar los datos-->
<div id="containerTable" style="width: 603px;overflow: scroll;">
<table>
    <tr>
        <th>id</th>
        <th>RUC</th>
        <th>Nombre</th>
        <th>Direccion</th>        
        <th>Departamento</th>
        <th>Provincia</th>		
        <th>Distrito</th>		
        <th>Telefono Fijo</th>
        <th>Telefono Celular</th>
        <th>Correo</th>
        <th>Costo</th>	
        <th>Observacion</th>
        <th>User</th>
        <th>Fecha</th>		
        <th>&nbsp;</th>                
        <th>&nbsp;</th>        
    </tr>
<!--recorro el arreglo de datos-->
    <?php foreach ($this->datos as $d) : ?>

        <tr>

        <td>
            <a href="<?php echo $this->url(array('controller' => 'cementerio','action' => 'update', 'id' => $d->idcementerio)); ?>"> 
                <?php echo $d->idcementerio; ?>
            </a>
        </td>
              
        <td><?php echo $d->RUC; ?></td>
                   
        <td><?php echo $d->nombre; ?></td>
                        
        <td><?php echo $d->direccion; ?></td>
                       
        <td><?php echo "xxx"; ?></td>
                   
        <td><?php echo "xxx"; ?></td>
                 
        <td><?php echo $d->iddistrito; ?></td>

        <td><?php echo $d->telefono_fijo; ?></td>

        <td><?php echo $d->telefono_celular; ?></td>

        <td><?php echo $d->mail; ?></td>

        <td><?php echo $d->costo; ?></td>
		
        <td><?php echo $d->observacion; ?></td>		
		
        <td><?php echo $d->user; ?></td>

        <td><?php echo $d->fecha; ?></td>	
						 

        <td>
            <a href="<?php echo $this->url(array('controller' => 'cementerio','action' => 'update', 'id' => $d->idcementerio)); ?>"> 
                <img src="<?php echo $this->baseUrl ?>/images/ico-editar.gif" title="Editar">
            </a>
        </td>
        
        <td>

            <a href="<?php echo $this->url(array('controller' => 'cementerio',
                       'action' => 'delete', 'id' => $d->idcementerio)); ?>">
                <img src="<?php echo $this->baseUrl ?>/images/eliminar.png" title="Eliminar">
            </a>
        </td>
        
        </tr>
<!--    fin del for-->
    <?php endforeach; ?>
</table>
</div>