<ul>
			<li><a href="<?php echo $this->url(array('controller' => 'velatorio','action' => 'index')); ?>">VELATORIO</a></li>
			<li><a href="<?php echo $this->url(array('controller' => 'cementerio','action' => 'index')); ?>">CEMENTERIO</a></li>
			<li><a href="<?php echo $this->url(array('controller' => 'crematorio','action' => 'index')); ?>">CREMATORIO</a></li>
			<li><a href="<?php echo $this->url(array('controller' => 'departamento','action' => 'index')); ?>">DEPARTAMENTO</a></li>
			<li><a href="<?php echo $this->url(array('controller' => 'provincia','action' => 'index')); ?>">PROVINCIA</a></li>
			<li><a href="<?php echo $this->url(array('controller' => 'distrito','action' => 'index')); ?>">DISTRITO</a></li>     
			<li><a href="<?php echo $this->url(array('controller' => 'marca','action' => 'index')); ?>">Marca</a></li>                         			
</ul>
		
		