<fieldset>
<legend>Capilla</legend>
<?php echo $this->form; ?>
</fieldset>

<style>
fieldset{

	border: 1px solid;
	
}


#fieldset-left{
	float:left;
	border:none;
}

#fieldset-right{
	float:left;
	border:none;	
}

#fieldset-bottom{
	clear:both;
	border:none;	
}

#observacion{
	height: 50px;
}


#idcapilla-label{
	display:none;
}

#submitbutton{
	margin-left: 229px;
}


</style>

<script src="http://code.jquery.com/jquery-1.10.0.min.js"></script>

<script>


$('dl').addClass('dl-horizontal');



</script>
