<link rel="stylesheet" href="<?php echo $this->baseUrl ?>/assets/data-tables/DT_bootstrap.css" />

<style>

/*
#submitbutton{
	margin-left: 229px;
}
*/
</style>


<script>

$(document).ready(function(){
    
    
    $('dl').addClass('dl-horizontal');
    $('dd').height('40px')
    $('#RUC').attr('placeholder','digite 11 digitos')
    $('#observacion').attr('rows','5')
    $('#submitbutton').addClass('btn btn-primary');
	
        
    //combos dependientes    
    $('#iddepartamento').change( function(e){

            var codDepa = $(this).val()
            //alert(codDepa)
            $.get('<?php echo $this->url(array('controller' => 'proveedor','action' => 'listarprov') ); ?>',{  codDepa:codDepa }, function(data) {

                    $('#idprovincias').empty()	
                    $('#iddistrito').empty()	

                    $('#idprovincias').append("<option value='0'>select</option>")			
                    $.each($.parseJSON(data), function(index, value) {
                            $('#idprovincias').append("<option value="+value[0]+">"+value[1]+"</option>")

                    });

            });


    })


    $('#idprovincias').change( function(e){

            var codDistr = $(this).val()
            $.get('<?php echo $this->url(array('controller' => 'proveedor','action' => 'listardistri') ); ?>',{  codDistr:codDistr }, function(data) {

                    $('#iddistrito').empty()

                    $('#iddistrito').append("<option value='0'>select</option>")			
                    $.each($.parseJSON(data), function(index, value) {
                            $('#iddistrito').append("<option value="+value[0]+">"+value[1]+"</option>")

                    });

            });


    })
})
    
</script>

 <!-- BEGIN Content -->
            <div id="main-content">
                <!-- BEGIN Page Title -->
                <div class="page-title">
                    <div>
                        <h1><i class="icon-file-alt"></i> Privilegios</h1>
                        <h4>Mantenimiento de Privilegios</h4>
                    </div>
                </div>
                <!-- END Page Title -->

                <!-- BEGIN Breadcrumb -->
                <div id="breadcrumbs">
                     <ul class="breadcrumb">
                        <li>
                            <i class="icon-home"></i>
                            <a href="<?php echo $this->baseUrl ?>">Home</a>
                            <span class="divider"><i class="icon-angle-right"></i></span>
                        </li>
                        <li>
                            <a href="<?php echo $this->baseUrl ?>/permisos">Permisos</a>
                            <span class="divider"><i class="icon-angle-right"></i></span>                        
                        </li>
                        <li class="active">Agregar
                        </li>
                        
                    </ul>
                </div>
                <!-- END Breadcrumb -->

                <!-- BEGIN Main Content -->
                <div class="row-fluid">
                    <div class="span12">
                        <div class="box">
                            <div class="box-title">
                                <h3><i class="icon-table"></i> Nuevo permiso</h3>
                                <div class="box-tool">
                                    <a data-action="collapse" href="#"><i class="icon-chevron-up"></i></a>
                                    <a data-action="close" href="#"><i class="icon-remove"></i></a>
                                </div>
                            </div>
                            <div class="box-content">
                              
<fieldset>
<?php echo $this->form; ?>
</fieldset>
                                
                                
                            </div>
                        </div>
                    </div>
                </div>
            
            
        <!--page specific plugin scripts-->
        <script type="text/javascript" src="<?php echo $this->baseUrl ?>/assets/data-tables/jquery.dataTables.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl ?>/assets/data-tables/DT_bootstrap.js"></script>
            


