<fieldset>
<legend>Velatorio</legend>
<?php echo $this->form; ?>
</fieldset>

<style>
fieldset{

	border: 1px solid;
	
}


#fieldset-left{
	float:left;
	border:none;
}

#fieldset-right{
	float:left;
	border:none;	
}

#fieldset-bottom{
	clear:both;
	border:none;	
}

#idcapilla-label{
	display:none;
}

#submitbutton{
	margin-left: 229px;
}


</style>

<script src="http://code.jquery.com/jquery-1.10.0.min.js"></script>

<script>

$('dl').addClass('dl-horizontal');

</script>

<script>


	$('#iddepartamento').change( function(e){

		var codDepa = $(this).val()
		$.get('../crematorio/listarprov',{  codDepa:codDepa }, function(data) {
			
			$('#idprovincias').empty()	
			$('#iddistrito').empty()	
			
			$('#idprovincias').append("<option value='0'>select</option>")			
			$.each($.parseJSON(data), function(index, value) {
				$('#idprovincias').append("<option value="+value[0]+">"+value[1]+"</option>")
			  
			});

		});
			
		
	})


	$('#idprovincias').change( function(e){

		var codDistr = $(this).val()
		$.get('../crematorio/listardistri',{  codDistr:codDistr }, function(data) {
			
			$('#iddistrito').empty()

			$.each($.parseJSON(data), function(index, value) {
				$('#iddistrito').append("<option value="+value[0]+">"+value[1]+"</option>")
			  
			});

		});
			
		
	})

    
</script>

